name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: cbrzeszczot/wonderful:wswan-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Update libraries
        run: wf-pacman -Syu --noconfirm && wf-pacman -Su --noconfirm

      - name: Build
        run: make

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Test suite
          path: build/roms/

